name: Checkout
on: [push]
jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files Before
        run: ls -a

      - name: Clone the code
        uses: actions/checkout@v4

      - name: List files After
        run: ls -a

  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files Before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List files After
        run: ls -a
