name: Concurrency 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment'
        type: environment
        required: true

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
