name: Manually Triggered
on:
  workflow_dispatch:
jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - name: Do sometrhing
        run: echo $GITHUB_REF
      - name: log something
        run: echo "Hello World"
