name: Matrix
on: [push]
jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, max]
        node-version: [14, 15, 16]
        #   max-parallel: 3
      fail-fast: true
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - run: node -v

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: node -v
