name: Status Check Functions
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step-2
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on Failure
        if: failure()
        run: echo 'Runs only on failure'
      - name: Runs on Success
        run: echo 'Runs on Success'
      - name: Always Runs
        if: always()
        run: echo 'Always Runs'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'
