name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Kinawy'
        required: false
jobs:
  calling-a-reusable-wf:
    uses: mahmmoudkinawy/jubilant-meme-ci/.github/workflows/reusable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets: inherit
