name: Workflow commands
on: [push]
jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message with paramters
        run: echo "::error::title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting an error message with paramters
        run: echo "::error::title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Setting an error message with paramters
        run: echo "::error::title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
      - name: Group of logs
        run: |
            echo "::group::My group title"
            echo "Inside group"
            echo "::endgroup::"
      - name: Masking a value
        run: echo "::add-mask::Secret string"
      - name: Echo a secret
        run: echo "Secret String"